export const pokemonTypeColors: any = {
    grass: "#B8E6B8",
    fire: "#FFD1B3",
    water: "#B7D8FF",
    electric: "#FFF2B3",
    psychic: "#FFC6E5",
    ice: "#D9F7F7",
    dragon: "#D6C6FF",
    dark: "#C7B8B8",
    fairy: "#FFD9F5",
    normal: "#E8E8D0",
    fighting: "#F5B7B1",
    flying: "#D7CCFF",
    poison: "#E2C2FF",
    ground: "#F7E0B5",
    rock: "#DDD0A8",
    bug: "#D8E8A8",
    ghost: "#CFC3E9",
    steel: "#DADAE8",
};